name: laravel
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                laravel: [ "6.0", "7.0", "8.0", "9.0", "10.0" ]
                php: [ "8.0", "8.1" ]
                excludes:
                    -   laravel: "6.0"
                        php: "8.1"

                    -   laravel: "7.0"
                        php: "8.1"

                    -   laravel: "10.0"
                        php: "8.0"

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit --ansi
